name: The Eureka Market
favicon: null
layout_spectrum: 0.05781935807317495
typography_spectrum: 0.6626597053837031
title: The Eureka Market on The Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9fa3a3'
    - '#0c0e0f'
    - '#ced0d1'
    - '#7a3f27'
  brandStrength: 0.7521180065814406
  lightness: 0.6483031662646681
  saturation: 0.059000075329095125
  rhythmicContrast: 0.7766918044071645
purpose: []
